### PR TITLE
Updated code to make it work with Swift 3.0 PREVIEW 6 on Ubuntu

### PR DESCRIPTION
**Pull request by rbukovansky**
These updates make SwiftCLI "compileable" with Swift 3.0 PREVIEW 6 on my Ubuntu installation resolving #18.

Just followed compilation errors and Foundation library docs to remove issues.

BTW You need to check class function checkForPipedData() in Input.swift as I wasn't sure how to solve the issue, so I just commented out problematic lines. Can be Swift guys corrected behavior you were trying to solve with this function and now it works OK.

Feel free to comment.

BTW Thanks a lot for SwiftCLI, it's making creating my app much more easier.

### CODE REVIEW

**Comment by jakeheis** [comment]
Your changes broke compilation on Mac unfortunately -- it seems as though these issues are caused by discrepancies between Swift Foundation and Objective-C Foundation. Commits 810821bd9960f8037781dc1abb179727c777e2d0 and  b391d9f2c2921d1475f55ef51cd7f94381a77c51 should fix these issues for now, but by the time Swift 3 is released, these changes should no longer be necessary

**Comment by rbukovansky** [comment]
That breakage was unintentional. I don't have Mac so I couldn't test it. Thanks for code updates.
